<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SeguridadSocialRadio</name>
   <tag></tag>
   <elementGuidId>a7ce37fb-075a-47f5-a96a-1d83b7c26b13</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='seguridadSocial']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;seguridadSocial&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>(//*[@formcontrolname='seguridadSocial'])[${index}]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>radio</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//*[@formcontrolname='seguridadSocial'])[${index}]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='seguridadSocial']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/div/input</value>
   </webElementXpaths>
</WebElementEntity>
