<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Crear Cliente</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>f709e6e9-3cc9-42a5-b01b-dc2a2b8386b9</testSuiteGuid>
   <testCaseLink>
      <guid>2e7051f0-9048-4d9f-8db4-6e73b8817bf9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Cliente/Crear Microempresario Persona Natural</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4ea833a7-a843-4c01-9715-b9fb5b22610c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c4364692-2431-4f56-95ca-a25e8dd9bfd3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f70a2ffb-d0f2-40bf-a454-04268249eb25</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>980e50c6-571e-4bf3-9b31-1d7688a3797d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Cliente/Crear Microempresario Persona Juridica</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4ea833a7-a843-4c01-9715-b9fb5b22610c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c4364692-2431-4f56-95ca-a25e8dd9bfd3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3d940bdd-d580-4aee-a8fc-c6a7156c8769</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
