<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Parametricas</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>60b8b923-2ff8-473a-819a-730756e7d8f0</testSuiteGuid>
   <testCaseLink>
      <guid>3d2edbb9-b30c-4b00-bd92-2324e61c3dc9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Intermediario/Administrar Lineas Propias</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>25a153bc-3108-4095-850d-b99003e9c066</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Intermediario/Administrar Montos por intermediarios</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fbd83594-8760-47bb-bb84-0c4eed84bc46</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>530ad267-e362-4d53-95f7-69223f7e6f16</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1fdacb6f-a7f4-426a-a809-8d8a165157ab</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>83c599e5-9aac-480f-89f3-b250c96eb3a3</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
