<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Solicitud</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>21767421-afc1-44db-8809-5174b8c2f138</testSuiteGuid>
   <testCaseLink>
      <guid>a3cc94ed-8496-4536-af85-794ecfe67710</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Cliente/Crear Solicitud</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d29b0e4b-5c10-427c-ab34-0d333eba8330</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6ca4c5c3-94dc-478e-b37f-4ba2eb286743</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>89c034c6-6359-4ca0-8de4-42481c7a0d52</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b2b6501b-78ed-4f5d-a4b5-45ccd4d549b9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f5b15c88-2e29-4e28-a7bc-d778dfe5592f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>69a5ff6d-9add-4637-96b9-dd0e6751accc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3e5a612d-8839-4796-a517-8403817d1e0e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Bancoldex/Aprobar Solicitud Bancoldex</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>79d84e73-7388-4526-92aa-3336b37e07fa</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Intermediario/Crear Propuesta Intermediario</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>59de38ea-e9a7-4f98-b604-2c992a185836</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>008fc2aa-868a-4e74-adfa-b6e1d3afb9f7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Intermediario/Aprobar Propuesta Intermediario</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>c2da6256-6e51-4992-895e-8b5bd0d7207b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Cliente/Seleccionar Propuesta Microempresario</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>31934ffc-7d93-42f7-997e-3c3f341ea207</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Intermediario/Confirmar Desembolso</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
