<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>EliminarMontoButton</name>
   <tag></tag>
   <elementGuidId>9a78c38b-b77e-4d22-889b-a39d089fe0d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//td[contains(text(),'20,000,001')]/..//i)[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//td[contains(text(),'20,000,001')]/..//i)[2]</value>
   </webElementProperties>
</WebElementEntity>
