<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Rut</name>
   <tag></tag>
   <elementGuidId>ca740869-21e7-4395-9275-2f5603464c41</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//*[@class='form-check']//input[@name='tieneRUT'])[${index}]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//*[@class='form-check']//input[@name='tieneRUT'])[${index}]</value>
      <webElementGuid>af32ad5a-7cd8-4fc7-98cb-f06e2bf6d7be</webElementGuid>
   </webElementProperties>
</WebElementEntity>
