<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TerminocondicionesRadio</name>
   <tag></tag>
   <elementGuidId>2520275c-ab99-4c14-af51-6e294119ac92</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//div[@class='form-check']/input)[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#login > div.container.mt-lg-4 > formulario-persona-natural > form > div > div.politicas > div > div:nth-child(2) > input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>terminosCondiciones</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//div[@class='form-check']/input)[2]</value>
   </webElementProperties>
</WebElementEntity>
