<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Municipio</name>
   <tag></tag>
   <elementGuidId>62897d95-de50-41a6-a499-d39805d0f935</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='miselectCiu']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;miselectCiu&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>miselectCiu</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>idCiudad</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Seleccione una opcionAGUA DE DIOS ALBAN ALBAN ANAPOIMA ANAPOIMA ANOLAIMA ANOLAIMA APULO ARBELAEZ ARBELAEZ BELTRAN BITUIMA BOJACA BOJACA Bosa                                    CABRERA CABRERA CACHIPAY CACHIPAY CAJICA CAJICA CAPARRAPI CAPARRAPI CAQUEZA CAQUEZA CARMEN DE CARUPA CARMEN DE CARUPA CHAGUANI CHAGUANI CHIA CHIA CHIPAQUE CHIPAQUE CHOACHI CHOACHI CHOCONTA COGUA COGUA COTA COTA CUCUNUBA CUCUNUBA Capellania Cundinamarca                 EL COLEGIO EL PENON EL ROSAL Engativa                                FACATATIVA FACATATIVA FOMEQUE FOMEQUE FOSCA FOSCA FUNZA FUNZA FUQUENE FUSAGASUGA Fontibon                                GACHALA GACHANCIPA GACHANCIPA GACHETA GAMA GIRARDOT GIRARDOT GRANADA GRANADA GUACHETA GUACHETA GUADUAS GUADUAS GUASCA GUASCA GUATAQUI GUATAVITA GUATAVITA GUAYABAL DE SIQUIMA GUAYABAL DE SIQUIMA GUAYABETAL GUAYABETAL GUTIERREZ Granada                                 JERUSALEN JERUSALEN JUNIN LA CALERA LA CALERA LA MESA LA MESA LA PALMA LA PALMA LA PENA LA PENA LA VEGA LA VEGA LENGUAZAQUE MACHETA MADRID MADRID MANTA MEDINA MEDINA MOSQUERA MOSQUERA NARINO NARINO NEMOCON NILO NILO NIMAIMA NIMAIMA NOCAIMA NOCAIMA PACHO PACHO PAIME PANDI PANDI PARATEBUENO PARATEBUENO PASCA PASCA PUERTO SALGAR PUERTO SALGAR PULI QUEBRADANEGRA QUEBRADANEGRA QUETAME QUIPILE RICAURTE SAN ANTONIO DEL TEQUENDAMA SAN BERNARDO SAN CAYETANO SAN FRANCISCO SAN JUAN DE RIO SECO SASAIMA SASAIMA SESQUILE SESQUILE SIBATE SIBATE SILVANIA SILVANIA SIMIJACA SIMIJACA SOACHA SOACHA SOPO SOPO SUBACHOQUE SUBACHOQUE SUESCA SUESCA SUPATA SUPATA SUSA SUSA SUTATAUSA SUTATAUSA Santandercito                           TABIO TABIO TAUSA TAUSA TENA TENJO TENJO TIBACUY TIBACUY TIBIRITA TIBIRITA TOCAIMA TOCAIMA TOCANCIPA TOCANCIPA TOPAIPI UBALA UBAQUE UBAQUE UNE UNE UTICA UTICA Usme                                    VENECIA VERGARA VERGARA VIANI VIANI VILLA DE SAN DIEGO DE UBATE VILLA DE SAN DIEGO DE UBATE VILLAGOMEZ VILLAPINZON VILLAPINZON VILLETA VILLETA VIOTA VIOTA Veneciano Pérez                         YACOPI YACOPI ZIPACON ZIPACON ZIPAQUIRA ZIPAQUIRA </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wrapped_home&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;RegistrarUsuarioIF&quot;]/form[@class=&quot;custom-form ng-invalid ng-dirty ng-touched&quot;]/div[@class=&quot;row justify-content-md-center mt-4&quot;]/div[@class=&quot;col-12 col-sm-6&quot;]/div[@class=&quot;required form-label&quot;]/select[@class=&quot;form-control ng-untouched ng-pristine ng-invalid&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='miselectCiu']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wrapped_home']/div/div/form/div[5]/div[2]/div/select</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ciudad oficina*'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Campo obligatorio'])[9]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Campo obligatorio'])[10]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Roles Disponibles'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/select</value>
   </webElementXpaths>
</WebElementEntity>
