<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ListasSelect</name>
   <tag></tag>
   <elementGuidId>c0256c16-20e4-4a0e-be0d-fc0efb801f27</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//*[@data-toggle='dropdown'])[${index}]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//*[@data-toggle='dropdown'])[${index}]</value>
   </webElementProperties>
</WebElementEntity>
